#!/usr/bin/python3.4
import os, sys


def maxium(row):  # find greatest in giver row
    max1 = 0
    for j in row:
        if max1 < len(str(j)):
            max1 = len(str(j))
    return max1


def maxi(table1):  # for given box find greatest value in every row
    max1 = []
    for j in table1:
        max1.append(maxium(j))
    return max1


def greatest(table1):
    max1 = 0
    for i in table1:
        if max1 < len(i):
            max1 = len(i)
    return max1


def line(table, k='-', c='+'):
    m = maxi(table)
    for i, j in enumerate(m):
        print(c, k * (int(j)) + k + k, sep='', end='')
        if i == len(m) - 1:
            print(c)


def box(table):
    m = maxi(table)
    column = 0  # for column
    row = 0  # for row
    g = greatest(table)
    while row < g:
        if row == 0 or row == 1:
            line(table, '=')
        else:
            line(table)
        for j in table:
            if row <= len(j) - 1:
                print('| ', str(j[row]), ' ' * (m[column] - len(str(j[row])) + 1), sep='', end='')
                column = column + 1
            else:
                print('|  ', ' ' * (m[column]), sep='', end='')
                column = column + 1
            if column == len(table):
                print('|')
                row = row + 1
                column = 0
            if row == g:
                line(table)

if len(sys.argv) == 1:
    cwd = os.getcwd()
else:
    cwd = sys.argv[1]
hidden = []
d1 = []
dirt = []
s = []
file = []
for p, d, l in os.walk(cwd):
    d1.extend(d)
    s.extend(l)
    break
for i in s:
    if i.startswith('.'):
        hidden.append(i)
    else:
        file.append(i)
for i in d1:
    if i.startswith('.'):
        hidden.append(i)
    else:
        dirt.append(i)
hidden = sorted(hidden,key=str.lower)
hidden.insert(0, 'Hidden Files and Directories')
dirt = sorted(dirt,key=str.lower)
dirt.insert(0, 'Directories')
file = sorted(file,key=str.lower)
file.insert(0, 'Files')
box([dirt,file,hidden])
